import Head from "next/head";

import Layout from "@/layout";

export default function Home() {
  return (
    <div className="border-2 border-black m-10 rounded-3xl shadow shadow-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>Content</h1>
      </Layout>
    </div>
  );
}
