import Head from "next/head";

import { Inter } from "next/font/google";
import Header from "@/components/header/index";
import Footer from "@/components/footer/index";
import Layout from "@/layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>Content</h1>
      </Layout>
    </>
  );
}
